CONNECT sys/dev@lbactest AS sysdba;

DROP USER LECTURER1;
CREATE USER LECTURER1 IDENTIFIED BY dev;
GRANT CREATE SESSION TO LECTURER1;

DROP USER LECTURER2;
CREATE USER LECTURER2 IDENTIFIED BY dev;
GRANT CREATE SESSION TO LECTURER2;

DROP USER LECTURER3;
CREATE USER LECTURER3 IDENTIFIED BY dev;
GRANT CREATE SESSION TO LECTURER3;

DROP USER PUBLIC1;
CREATE USER PUBLIC1 IDENTIFIED BY dev;
GRANT CREATE SESSION TO PUBLIC1;

CONNECT dev/dev@lbactest;

GRANT SELECT, UPDATE ON UNIVERSITYRESOURCE TO LECTURER1;

GRANT SELECT, UPDATE ON UNIVERSITYRESOURCE TO LECTURER2;

GRANT SELECT, UPDATE ON UNIVERSITYRESOURCE TO LECTURER3;

GRANT SELECT ON UNIVERSITYRESOURCE TO PUBLIC1;

