ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; 
ALTER SESSION SET CURRENT_SCHEMA = dev;

-- Creating Roles

DROP    ROLE STUDENT;
CREATE  ROLE STUDENT;

DROP    ROLE LECTURER;
CREATE  ROLE LECTURER;

DROP    ROLE FINANCE;
CREATE  ROLE FINANCE;

DROP    ROLE COURSE_ADMIN;
CREATE  ROLE COURSE_ADMIN;

