ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; 
ALTER SESSION SET CURRENT_SCHEMA = dev;

-- Creating Roles

DROP    ROLE STUDENT;
CREATE  ROLE STUDENT;

DROP    ROLE STUDENT;
CREATE  ROLE STUDENT;

DROP    ROLE STUDENT;
CREATE  ROLE STUDENT;

DROP    ROLE ENROLLMENT_ADMIN;
CREATE  ROLE ENROLLMENT_ADMIN;
