ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; 
ALTER SESSION SET CURRENT_SCHEMA = dev;

-- Creating Users

DROP USER USER1;

CREATE USER USER1 IDENTIFIED BY PASSWORD1;
GRANT STUDENT, CREATE SESSION TO USER1;


INSERT INTO RoleMap
(
    user_id,
    role_name
)
VALUES
(
    'USER1',
    'STUDENT'
);