ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; 
ALTER SESSION SET CURRENT_SCHEMA = dev;

-- Creating Users

DROP USER PUBLIC1;
CREATE USER PUBLIC1 IDENTIFIED BY PASSWORD;
GRANT CREATE SESSION TO PUBLIC1;

DROP USER STUDENT1;
CREATE USER STUDENT1 IDENTIFIED BY PASSWORD;
GRANT STUDENT, CREATE SESSION TO STUDENT1;
INSERT INTO RoleMap (user_id, role_name) VALUES ('STUDENT1', 'STUDENT');

DROP USER LECTURER1;
CREATE USER LECTURER1 IDENTIFIED BY PASSWORD;
GRANT LECTURER, CREATE SESSION TO LECTURER1;
INSERT INTO RoleMap (user_id, role_name) VALUES ('LECTURER1', 'LECTURER');

DROP USER LECTURER2;
CREATE USER LECTURER2 IDENTIFIED BY PASSWORD;
GRANT LECTURER, CREATE SESSION TO LECTURER2;
INSERT INTO RoleMap (user_id, role_name) VALUES ('LECTURER2', 'LECTURER');

DROP USER FINANCE1;
CREATE USER FINANCE1 IDENTIFIED BY PASSWORD;
GRANT FINANCE, CREATE SESSION TO FINANCE1;
INSERT INTO RoleMap (user_id, role_name) VALUES ('FINANCE1', 'FINANCE');
