ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; 
ALTER SESSION SET CURRENT_SCHEMA = dev;

-- Creating Users

DROP USER STUDENT1;
CREATE USER STUDENT1 IDENTIFIED BY PASSWORD1;
GRANT STUDENT, CREATE SESSION TO STUDENT1;
INSERT INTO RoleMap (user_id, role_name) VALUES ('STUDENT1', 'STUDENT');

DROP USER LECTURER1;
CREATE USER LECTURER1 IDENTIFIED BY PASSWORD1;
GRANT LECTURER, CREATE SESSION TO LECTURER1;
INSERT INTO RoleMap (user_id, role_name) VALUES ('LECTURER1', 'LECTURER');
