ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; 
ALTER SESSION SET CURRENT_SCHEMA = dev;

-- Creating Row Level Security

-- SELECT SYS_CONTEXT('SYS_SESSION_ROLES', 'DBA') FROM DUAL;
-- SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') FROM DUAL; 

CREATE OR REPLACE FUNCTION StudentGrade(v_schema IN VARCHAR2, v_obj IN VARCHAR2)
RETURN VARCHAR2 IS condition VARCHAR2(200);
BEGIN
    IF (SYS_CONTEXT('SYS_SESSION_ROLES', 'Student') = 'TRUE') THEN
        condition := 'student_id = SYS_CONTEXT(''USERENV'', ''SESSION_USER'')';
    ELSE
        condition := '';
    END IF;
    RETURN condition;
END;
/
