SET ROLE LECTURER;

SET SERVEROUTPUT ON;

-- SELECT SYS_CONTEXT('SYS_SESSION_ROLES', 'DBA') FROM DUAL;
-- SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') FROM DUAL; 

DECLARE is_lecturer VARCHAR(200);
BEGIN
    SELECT SYS_CONTEXT('SYS_SESSION_ROLES', 'LECTURER') INTO is_lecturer FROM DUAL;
    IF is_lecturer = 'TRUE' THEN
        DBMS_OUTPUT.PUT_LINE('Test Starting');

        SELECT * FROM dev.Payroll;
    ELSE
        DBMS_OUTPUT.PUT_LINE('Not Logged in as Lecturer');
    END IF;
END;

/
